name: "Greet"
# description: "Greet someone"

inputs:
  name:
    description: "The name of the caller to greet."
    required: true
    default: "Unknown"

outputs:
  random:
    description: "Random number"
    value: ${{ steps.random-number.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Test Interpolation ${{inputs.name}}
      run: echo Hello ${{inputs.name}}.
      shell: bash
    - id: random-number
      run: echo "::set-output name=random::$(echo $RANDOM)"
      shell: bash        
    - run: echo Goodbye ${{inputs.name}}.
      shell: bash
